image: node:latest

cache:
  paths:
    - node_modules/
    - dist/

before_script:
  - node -v
  - curl -L https://fly.io/install.sh | sh
  - /root/.fly/bin/flyctl --help

stages:
  - build
  - deploy

dependencies_and_building:
    stage: build
    script:
        - echo "Building"
        - npm i
        - npm run build
    artifacts:
        paths:
            - node_modules/
            - dist/
    
deployment_app:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - /root/.fly/bin/flyctl auth token $FLY_API_TOKEN
    - /root/.fly/bin/flyctl --app zinkapi deploy 
