version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: curl -L https://fly.io/install.sh | sh
      - run: /home/circleci/.fly/bin/flyctl auth token ${FLY_API_TOKEN}
      - run: curl -o prod.env ${ENV_URI}
      - node/install-packages
      - run: npm run build
      - run: /home/circleci/.fly/bin/flyctl --app ${APP_NAME} deploy

  deployment:
    docker:
      - image: cimg/base:2020.09
    steps:
      - run: dir
      - run: /home/circleci/.fly/bin/flyctl --app ${APP_NAME} deploy
        
workflows:
  build-deploy:
    jobs:
      - build
