on: [ push, pull_request ]

name: Testing
    
jobs:
  test:
    name: "ðŸ§ª Testing"
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: App Testing
        run: |
          npm i
          node ./scripts/secrets --write
          npm run test:e2e
  